# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temperature.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='temperature.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11temperature.proto\"6\n\x16TemperatureMeasurement\x12\x1c\n\x14temperatureRecording\x18\x01 \x01(\x05\"8\n\x10TemperatureEntry\x12\x11\n\trecording\x18\x01 \x01(\x05\x12\x11\n\tpersisted\x18\x02 \x01(\x08\x32\x63\n\x14TemperatureRecording\x12K\n\x1bTemperatureMeasurementStats\x12\x17.TemperatureMeasurement\x1a\x11.TemperatureEntry\"\x00\x62\x06proto3'
)




_TEMPERATUREMEASUREMENT = _descriptor.Descriptor(
  name='TemperatureMeasurement',
  full_name='TemperatureMeasurement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperatureRecording', full_name='TemperatureMeasurement.temperatureRecording', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=75,
)


_TEMPERATUREENTRY = _descriptor.Descriptor(
  name='TemperatureEntry',
  full_name='TemperatureEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recording', full_name='TemperatureEntry.recording', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='persisted', full_name='TemperatureEntry.persisted', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['TemperatureMeasurement'] = _TEMPERATUREMEASUREMENT
DESCRIPTOR.message_types_by_name['TemperatureEntry'] = _TEMPERATUREENTRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TemperatureMeasurement = _reflection.GeneratedProtocolMessageType('TemperatureMeasurement', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATUREMEASUREMENT,
  '__module__' : 'temperature_pb2'
  # @@protoc_insertion_point(class_scope:TemperatureMeasurement)
  })
_sym_db.RegisterMessage(TemperatureMeasurement)

TemperatureEntry = _reflection.GeneratedProtocolMessageType('TemperatureEntry', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATUREENTRY,
  '__module__' : 'temperature_pb2'
  # @@protoc_insertion_point(class_scope:TemperatureEntry)
  })
_sym_db.RegisterMessage(TemperatureEntry)



_TEMPERATURERECORDING = _descriptor.ServiceDescriptor(
  name='TemperatureRecording',
  full_name='TemperatureRecording',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=135,
  serialized_end=234,
  methods=[
  _descriptor.MethodDescriptor(
    name='TemperatureMeasurementStats',
    full_name='TemperatureRecording.TemperatureMeasurementStats',
    index=0,
    containing_service=None,
    input_type=_TEMPERATUREMEASUREMENT,
    output_type=_TEMPERATUREENTRY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEMPERATURERECORDING)

DESCRIPTOR.services_by_name['TemperatureRecording'] = _TEMPERATURERECORDING

# @@protoc_insertion_point(module_scope)
